version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ClaimsModule.Host\Dockerfile
    ports:
      - "5032:8081"
    depends_on:
      - mysql
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=claims-module;user=root;password=password;

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: claims-module
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
